"""Add idempotency_hash to WebhookLog model

Revision ID: 06a058cc85f0
Revises: f157861935ef
Create Date: 2025-06-27 16:05:34.447774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a058cc85f0'
down_revision = 'f157861935ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_webhook_logs_idempotency_hash'), ['idempotency_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_logs_idempotency_hash'))
        batch_op.drop_column('idempotency_hash')

    # ### end Alembic commands ###
