"""Add trading_strategies and strategy_value_history tables with stricter comparison

Revision ID: 0f5e3bcbce32
Revises: 5b2d509f47b7
Create Date: 2025-06-07 18:34:25.071883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5e3bcbce32'
down_revision = '5b2d509f47b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_caches', schema=None) as batch_op:
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('invalid_credentials',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('invalid_credentials',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               existing_nullable=True)

    with op.batch_alter_table('account_caches', schema=None) as batch_op:
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'coinbase'"),
               existing_nullable=True)

    # ### end Alembic commands ###
