"""add oauth credentials table

Revision ID: 101c1366fcce
Revises: ee7b0f7d887e
Create Date: 2025-02-16 17:17:35.169479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101c1366fcce'
down_revision = 'ee7b0f7d887e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_credentials', schema=None) as batch_op:
        batch_op.alter_column('automation_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_credentials', schema=None) as batch_op:
        batch_op.alter_column('automation_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
