"""Add indexes to webhook logs

Revision ID: 3f5665c11741
Revises: 
Create Date: 2025-03-17 08:27:57.435129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5665c11741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_logs_automation_id'), ['automation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_webhook_logs_automation_id'))

    # ### end Alembic commands ###
