"""add client_order_id and other fields to webhook_logs

Revision ID: 49fb25bf2a3a
Revises: 
Create Date: 2025-03-04 12:32:54.291414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fb25bf2a3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_order_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('raw_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.drop_column('raw_response')
        batch_op.drop_column('client_order_id')

    # ### end Alembic commands ###
