"""Add passphrase field to exchange credentials

Revision ID: 5b2d509f47b7
Revises: f2d64d5a8b11
Create Date: 2025-05-30 13:37:38.346579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2d509f47b7'
down_revision = 'f2d64d5a8b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_caches', schema=None) as batch_op:
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'coinbase'"))

    with op.batch_alter_table('exchange_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passphrase', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_credentials', schema=None) as batch_op:
        batch_op.drop_column('passphrase')

    with op.batch_alter_table('account_caches', schema=None) as batch_op:
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'coinbase'"))

    # ### end Alembic commands ###
