"""Add strategy_name and exchange_name to WebhookLog

Revision ID: 76fb434f9465
Revises: 8bed633f600b
Create Date: 2025-06-30 14:44:47.971709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fb434f9465'
down_revision = '8bed633f600b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('exchange_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.drop_column('exchange_name')
        batch_op.drop_column('strategy_name')

    # ### end Alembic commands ###
