"""add strategy_name columns to asset_transfer_logs

Revision ID: 83ad3530901e
Revises: f58bd72dc2cd
Create Date: 2025-07-16 13:01:41.702932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ad3530901e'
down_revision = 'f58bd72dc2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_transfer_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_name_from', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('strategy_name_to', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_transfer_logs', schema=None) as batch_op:
        batch_op.drop_column('strategy_name_to')
        batch_op.drop_column('strategy_name_from')

    # ### end Alembic commands ###
