"""Add target_type to WebhookLog model

Revision ID: 8bed633f600b
Revises: 06a058cc85f0
Create Date: 2025-06-27 16:30:11.964049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bed633f600b'
down_revision = '06a058cc85f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_webhook_logs_target_type'), ['target_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_logs_target_type'))
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
