"""Add asset_transfer_logs

Revision ID: 9c45d46f46c1
Revises: 76fb434f9465
Create Date: 2025-07-09 10:38:18.546333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c45d46f46c1'
down_revision = '76fb434f9465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_transfer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_identifier', sa.String(length=100), nullable=False),
    sa.Column('destination_identifier', sa.String(length=100), nullable=False),
    sa.Column('asset_symbol', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('strategy_id_from', sa.Integer(), nullable=True),
    sa.Column('strategy_id_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_transfer_logs')
    # ### end Alembic commands ###
