"""Add trading_pair field to Automation model

Revision ID: c3c9be6fd137
Revises: ddc9033e371f
Create Date: 2025-02-24 13:50:23.301530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c9be6fd137'
down_revision = 'ddc9033e371f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trading_pair', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_column('trading_pair')

    # ### end Alembic commands ###
