"""encrypt oauth tokens

Revision ID: ddc9033e371f
Revises: a495c2e5da7e
Create Date: 2025-02-23 10:35:11.563953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc9033e371f'
down_revision = 'a495c2e5da7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_refresh_attempt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refresh_error', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_valid', sa.Boolean(), nullable=True))
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_credentials', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('is_valid')
        batch_op.drop_column('refresh_error')
        batch_op.drop_column('last_refresh_attempt')

    # ### end Alembic commands ###
