"""Add automation_id to exchange_credentials

Revision ID: ee7b0f7d887e
Revises: a53235d8e008
Create Date: 2025-02-15 17:25:36.401395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7b0f7d887e'
down_revision = 'a53235d8e008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_credentials', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('automation_id', sa.String(length=50), nullable=True))
        
    # Add foreign key with explicit name
    with op.batch_alter_table('exchange_credentials', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_exchange_credentials_automation_id',
            'automations',
            ['automation_id'],
            ['automation_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_credentials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exchange_credentials_automation_id', type_='foreignkey')
        batch_op.drop_column('automation_id')

    # ### end Alembic commands ###